language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=">=1.4,<1.5" OSCAR_VERSION=">=0.6,<0.7"
  - DJANGO_VERSION=">=1.5,<1.6" OSCAR_VERSION=">=0.6,<0.7"
install:
  - pip install Django$DJANGO_VERSION django-oscar$OSCAR_VERSION
  - pip install .
  - pip install -r requirements.txt
script:
  - py.test --pep8 --cov oscar_support
after_success:
  - coveralls
